export const ATA_CHAPTERS = [
    { code: "05", title: "Time Limits/Maintenance Checks" },
    { code: "06", title: "Dimensions and Areas" },
    { code: "07", title: "Lifting and Shoring" },
    { code: "08", title: "Leveling and Weighing" },
    { code: "09", title: "Towing and Taxiing" },
    { code: "10", title: "Parking, Mooring, Storage and Return to Service" },
    { code: "11", title: "Placards and Markings" },
    { code: "12", title: "Servicing" },
    { code: "18", title: "Vibration and Noise Analysis" },
    { code: "20", title: "Standard Practices - Airframe" },
    { code: "21", title: "Air Conditioning" },
    { code: "22", title: "Auto Flight" },
    { code: "23", title: "Communications" },
    { code: "24", title: "Electrical Power" },
    { code: "25", title: "Equipment/Furnishings" },
    { code: "26", title: "Fire Protection" },
    { code: "27", title: "Flight Controls" },
    { code: "28", title: "Fuel" },
    { code: "29", title: "Hydraulic Power" },
    { code: "30", title: "Ice and Rain Protection" },
    { code: "31", title: "Indicating/Recording Systems" },
    { code: "32", title: "Landing Gear" },
    { code: "33", title: "Lights" },
    { code: "34", title: "Navigation" },
    { code: "35", title: "Oxygen" },
    { code: "36", title: "Pneumatic" },
    { code: "37", title: "Vacuum" },
    { code: "38", title: "Water/Waste" },
    { code: "39", title: "Electrical - Electronic Panels and Multipurpose Components" },
    { code: "41", title: "Water Ballast" },
    { code: "45", title: "Central Maintenance System (CMS)" },
    { code: "46", title: "Information Systems" },
    { code: "47", title: "Inert Gas System" },
    { code: "49", title: "Airborne Auxiliary Power" },
    { code: "51", title: "Standard Practices and Structures - General" },
    { code: "52", title: "Doors" },
    { code: "53", title: "Fuselage" },
    { code: "54", title: "Nacelles/Pylons" },
    { code: "55", title: "Stabilizers" },
    { code: "56", title: "Windows" },
    { code: "57", title: "Wings" },
    { code: "70", title: "Standard Practices - Engine" },
    { code: "71", title: "Power Plant" },
    { code: "72", title: "Engine" },
    { code: "73", title: "Engine - Fuel and Control" },
    { code: "74", title: "Ignition" },
    { code: "75", title: "Bleed Air" },
    { code: "76", title: "Engine Controls" },
    { code: "77", title: "Engine Indicating" },
    { code: "78", title: "Exhaust" },
    { code: "79", title: "Oil" },
    { code: "80", title: "Starting" }
] as const;

export const VEHICLE_CATEGORIES = [
    {
        id: "aircraft",
        label: "Aircraft",
        subcategories: ["Commercial", "General Aviation", "Rotary Wing", "Military"],
        standards: ["ATA iSpec 2200", "S1000D"]
    },
    {
        id: "automotive",
        label: "Automotive",
        subcategories: ["Passenger Cars", "Heavy Duty Trucks", "Electric Vehicles", "Commercial"],
        standards: ["SAE J1939", "OBD-II"]
    },
    {
        id: "marine",
        label: "Marine",
        subcategories: ["Commercial Shipping", "Yachts", "Offshore", "Naval"],
        standards: ["NMEA 2000"]
    }
] as const;
